name: SonarQube analysis

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR info
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Secret from SonarQube or SonarCloud
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # e.g., https://sonarcloud.io or your SonarQube URL
        with:
          args: >
            -Dsonar.projectKey=Maharajan-02_TutorManagement
            -Dsonar.projectName=TutorManagement
